# permissions for end users to edit bgrouters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgrouter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bgrouter
    app.kubernetes.io/part-of: bgrouter
    app.kubernetes.io/managed-by: kustomize
  name: bgrouter-editor-role
rules:
- apiGroups:
  - bgrouter.yashirook.github.io
  resources:
  - bgrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgrouter.yashirook.github.io
  resources:
  - bgrouters/status
  verbs:
  - get
