//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGRouter) DeepCopyInto(out *BGRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGRouter.
func (in *BGRouter) DeepCopy() *BGRouter {
	if in == nil {
		return nil
	}
	out := new(BGRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGRouterList) DeepCopyInto(out *BGRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGRouterList.
func (in *BGRouterList) DeepCopy() *BGRouterList {
	if in == nil {
		return nil
	}
	out := new(BGRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGRouterSpec) DeepCopyInto(out *BGRouterSpec) {
	*out = *in
	in.VirtualServiceConfig.DeepCopyInto(&out.VirtualServiceConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGRouterSpec.
func (in *BGRouterSpec) DeepCopy() *BGRouterSpec {
	if in == nil {
		return nil
	}
	out := new(BGRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGRouterStatus) DeepCopyInto(out *BGRouterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGRouterStatus.
func (in *BGRouterStatus) DeepCopy() *BGRouterStatus {
	if in == nil {
		return nil
	}
	out := new(BGRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualServiceConfig) DeepCopyInto(out *VirtualServiceConfig) {
	*out = *in
	if in.HostsForInClusterTraffic != nil {
		in, out := &in.HostsForInClusterTraffic, &out.HostsForInClusterTraffic
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostsForOutsideClusterTraffic != nil {
		in, out := &in.HostsForOutsideClusterTraffic, &out.HostsForOutsideClusterTraffic
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualServiceConfig.
func (in *VirtualServiceConfig) DeepCopy() *VirtualServiceConfig {
	if in == nil {
		return nil
	}
	out := new(VirtualServiceConfig)
	in.DeepCopyInto(out)
	return out
}
